--
-- Creating table TB_C_GETSUDO_MONTH
-- ===============================
--

CREATE TABLE "TB_C_GETSUDO_MONTH" (
"MONTH" VARCHAR2 (10) NOT NULL,
"DISPLAY_MONTH" NUMBER (2) NOT NULL,
"CHECK_MONTH" NUMBER (2) NOT NULL,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_C_GETSUDO_MONTH ADD CONSTRAINT PK_C_GETSUDO_MONTH PRIMARY KEY (MONTH ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_C_VEHICLE_PLANT
-- ===============================
--

CREATE TABLE "TB_C_VEHICLE_PLANT" (
"VEHICLE_PLANT" VARCHAR2 (20) NOT NULL,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_C_VEHICLE_PLANT ADD CONSTRAINT PK_C_VEHICLE_PLANT PRIMARY KEY (VEHICLE_PLANT ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_C_UNIT_PLANT
-- ===============================
--

CREATE TABLE "TB_C_UNIT_PLANT" (
"UNIT_PLANT" VARCHAR2 (20) NOT NULL,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_C_UNIT_PLANT ADD CONSTRAINT PK_C_UNIT_PLANT PRIMARY KEY (UNIT_PLANT ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_C_PACK_LT
-- ===============================
--

CREATE TABLE "TB_C_PACK_LT" (
"VEHICLE_PLANT" VARCHAR2 (20) NOT NULL,
"UNIT_PLANT" VARCHAR2 (20) NOT NULL,
"OFFSET_LT" NUMBER (1) NOT NULL,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_C_PACK_LT ADD CONSTRAINT PK_C_PACK_LT PRIMARY KEY (VEHICLE_PLANT , UNIT_PLANT ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_M_VEHICLE_PLANT
-- ===============================
--

CREATE TABLE "TB_M_VEHICLE_PLANT" (
"VEHICLE_PLANT" VARCHAR2 (20) NOT NULL,
"VEHICLE_MODEL" VARCHAR2 (30) NOT NULL,
"TC_FROM" DATE  NOT NULL,
"TC_TO" DATE ,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_M_VEHICLE_PLANT ADD CONSTRAINT PK_M_VEHICLE_PLANT PRIMARY KEY (VEHICLE_PLANT , VEHICLE_MODEL , TC_FROM ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_M_UNIT_PLANT
-- ===============================
--

CREATE TABLE "TB_M_UNIT_PLANT" (
"UNIT_PLANT" VARCHAR2 (20) NOT NULL,
"UNIT_MODEL" VARCHAR2 (30) NOT NULL,
"UNIT_PARENT_LINE" VARCHAR2 (5) NOT NULL,
"UNIT_SUB_LINE" VARCHAR2 (5) NOT NULL,
"UNIT_TYPE" VARCHAR2 (20) NOT NULL,
"TC_FROM" DATE  NOT NULL,
"TC_TO" DATE ,
"REMARK" VARCHAR2 (200),
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_M_UNIT_PLANT ADD CONSTRAINT PK_M_UNIT_PLANT PRIMARY KEY (UNIT_PLANT , UNIT_MODEL , UNIT_PARENT_LINE , UNIT_SUB_LINE , TC_FROM ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_M_VEHICLE_UNIT_RELATION
-- ===============================
--

CREATE TABLE "TB_M_VEHICLE_UNIT_RELATION" (
"VEHICLE_PLANT" VARCHAR2 (20) NOT NULL,
"VEHICLE_MODEL" VARCHAR2 (30) NOT NULL,
"UNIT_PLANT" VARCHAR2 (20) NOT NULL,
"UNIT_MODEL" VARCHAR2 (30) NOT NULL,
"UNIT_TYPE" VARCHAR2 (20) NOT NULL,
"PRIORITY" NUMBER (1) NOT NULL,
"TC_FROM" DATE  NOT NULL,
"TC_TO" DATE ,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_M_VEHICLE_UNIT_RELATION ADD CONSTRAINT PK_M_VEHICLE_UNIT_RELATION PRIMARY KEY (VEHICLE_PLANT , VEHICLE_MODEL , UNIT_PLANT , UNIT_MODEL , PRIORITY , TC_FROM ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_M_CALENDAR
-- ===============================
--

CREATE TABLE "TB_M_CALENDAR" (
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"PLANT" VARCHAR2 (20) NOT NULL,
"CALENDAR_DATE" DATE  NOT NULL,
"CALENDAR_FLAG" VARCHAR2 (1),
"PLANT_TYPE" VARCHAR2 (1),
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_M_CALENDAR ADD CONSTRAINT PK_M_CALENDAR PRIMARY KEY (GETSUDO_MONTH , TIMING , PLANT , CALENDAR_DATE ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_M_STD_STOCK
-- ===============================
--

CREATE TABLE "TB_M_STD_STOCK" (
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"VEHICLE_PLANT" VARCHAR2 (20) NOT NULL,
"VEHICLE_MODEL" VARCHAR2 (30) NOT NULL,
"UNIT_PLANT" VARCHAR2 (20) NOT NULL,
"UNIT_MODEL" VARCHAR2 (30) NOT NULL,
"STOCK_MONTH" VARCHAR2 (6) NOT NULL,
"STOCK_MIN" NUMBER (4,2),
"STOCK_MAX" NUMBER (4,2),
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_M_STD_STOCK ADD CONSTRAINT PK_M_STD_STOCK PRIMARY KEY (GETSUDO_MONTH , TIMING , VEHICLE_PLANT , VEHICLE_MODEL , UNIT_PLANT , UNIT_MODEL , STOCK_MONTH ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_M_UNIT_PLANT_CAPA
-- ===============================
--

CREATE TABLE "TB_M_UNIT_PLANT_CAPA" (
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"UNIT_PLANT" VARCHAR2 (20) NOT NULL,
"UNIT_PARENT_LINE" VARCHAR2 (5) NOT NULL,
"UNIT_SUB_LINE" VARCHAR2 (5) NOT NULL,
"UNIT_CAPA_MONTH" VARCHAR2 (6) NOT NULL,
"MONTHLY_CAPA" NUMBER (5),
"DAILY_CAPA" NUMBER (5),
"WORKING_DAY" NUMBER (2),
"WORKING_TIME" NUMBER (3),
"WORKING_SHIFT" NUMBER (1),
"TAKT_TIME" NUMBER (4,2),
"EFFICIENCY" NUMBER (5,2),
"DAILY_OT" NUMBER (4,2),
"HOLIDAY_OT" NUMBER (2),
"SPECIAL_EFFORT" NUMBER (4),
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_M_UNIT_PLANT_CAPA ADD CONSTRAINT PK_M_UNIT_PLANT_CAPA PRIMARY KEY (GETSUDO_MONTH , TIMING , UNIT_PLANT , UNIT_PARENT_LINE , UNIT_SUB_LINE , UNIT_CAPA_MONTH ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_R_KAIKIENG_H
-- ===============================
--

CREATE TABLE "TB_R_KAIKIENG_H" (
"VERSION" VARCHAR2 (10) NOT NULL,
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"VEHICLE_PLANT" VARCHAR2 (20) NOT NULL,
"VEHICLE_MODEL" VARCHAR2 (30) NOT NULL,
"VOLUME_MONTH" VARCHAR2 (6) NOT NULL,
"VEHICLE_VOLUME" NUMBER (5),
"KAIKIENG_FILE_NAME" VARCHAR2 (270),
"WORKSHEET_FILE_NAME" VARCHAR2 (270),
"SUBMIT_DT" DATE ,
"REJECT_DT" DATE ,
"KAIKIENG_STATUS" VARCHAR2 (2) NOT NULL,
"WORKSHEET_STATUS" VARCHAR2 (2),
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_R_KAIKIENG_H ADD CONSTRAINT PK_R_KAIKIENG_H PRIMARY KEY (VERSION , GETSUDO_MONTH , TIMING , VEHICLE_PLANT , VEHICLE_MODEL , VOLUME_MONTH ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

CREATE INDEX IX_R_KAIKIENG_H1 on TB_R_KAIKIENG_H (VERSION, GETSUDO_MONTH, TIMING)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
CREATE INDEX IX_R_KAIKIENG_H2 on TB_R_KAIKIENG_H (GETSUDO_MONTH, TIMING)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
CREATE INDEX IX_R_KAIKIENG_H3 on TB_R_KAIKIENG_H (VERSION, GETSUDO_MONTH, TIMING, VEHICLE_PLANT, VEHICLE_MODEL)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
--
-- Creating table TB_R_KAIKIENG_D
-- ===============================
--

CREATE TABLE "TB_R_KAIKIENG_D" (
"VERSION" VARCHAR2 (10) NOT NULL,
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"VEHICLE_PLANT" VARCHAR2 (20) NOT NULL,
"VEHICLE_MODEL" VARCHAR2 (30) NOT NULL,
"UNIT_TYPE" VARCHAR2 (20) NOT NULL,
"UNIT_MODEL" VARCHAR2 (30) NOT NULL,
"VOLUME_MONTH" VARCHAR2 (6) NOT NULL,
"UNIT_VOLUME" NUMBER (5),
"MULTI_SOURCE_FLAG" VARCHAR2 (1) NOT NULL,
"MULTI_SUB_LINE_FLAG" VARCHAR2 (1) NOT NULL,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_R_KAIKIENG_D ADD CONSTRAINT PK_R_KAIKIENG_D PRIMARY KEY (VERSION , GETSUDO_MONTH , TIMING , VEHICLE_PLANT , VEHICLE_MODEL , UNIT_MODEL , VOLUME_MONTH ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

CREATE INDEX IX_R_KAIKIENG_D1 on TB_R_KAIKIENG_D (VERSION, GETSUDO_MONTH, TIMING, VEHICLE_PLANT, VEHICLE_MODEL, UNIT_TYPE, UNIT_MODEL, VOLUME_MONTH)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
--
-- Creating table TB_R_WS_MULTI_SOURCE_UNITS
-- ===============================
--

CREATE TABLE "TB_R_WS_MULTI_SOURCE_UNITS" (
"VERSION" VARCHAR2 (10) NOT NULL,
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"VEHICLE_PLANT" VARCHAR2 (20) NOT NULL,
"VEHICLE_MODEL" VARCHAR2 (30) NOT NULL,
"UNIT_PLANT" VARCHAR2 (20) NOT NULL,
"UNIT_TYPE" VARCHAR2 (20) NOT NULL,
"UNIT_MODEL" VARCHAR2 (30) NOT NULL,
"VOLUME_MONTH" VARCHAR2 (6) NOT NULL,
"UNIT_VOLUME" NUMBER (5),
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_R_WS_MULTI_SOURCE_UNITS ADD CONSTRAINT PK_R_WS_MULTI_SOURCE_UNITS PRIMARY KEY (VERSION , GETSUDO_MONTH , TIMING , VEHICLE_PLANT , VEHICLE_MODEL , UNIT_PLANT , UNIT_MODEL , VOLUME_MONTH ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

CREATE INDEX IX_R_WS_MULTI_SOURCE_UNITS1 on TB_R_WS_MULTI_SOURCE_UNITS (VERSION, GETSUDO_MONTH, TIMING, VEHICLE_PLANT, VEHICLE_MODEL, UNIT_PLANT, UNIT_TYPE, UNIT_MODEL, VOLUME_MONTH)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
--
-- Creating table TB_R_WS_PACKING_MOVEMENT
-- ===============================
--

CREATE TABLE "TB_R_WS_PACKING_MOVEMENT" (
"VERSION" VARCHAR2 (10) NOT NULL,
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"VEHICLE_PLANT" VARCHAR2 (20) NOT NULL,
"VEHICLE_MODEL" VARCHAR2 (30) NOT NULL,
"UNIT_PLANT" VARCHAR2 (20) NOT NULL,
"UNIT_TYPE" VARCHAR2 (20) NOT NULL,
"UNIT_MODEL" VARCHAR2 (30) NOT NULL,
"VOLUME_MONTH" VARCHAR2 (6) NOT NULL,
"PACKING_VOLUME" NUMBER (5),
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_R_WS_PACKING_MOVEMENT ADD CONSTRAINT PK_R_WS_PACKING_MOVEMENT PRIMARY KEY (VERSION , GETSUDO_MONTH , TIMING , VEHICLE_PLANT , VEHICLE_MODEL , UNIT_PLANT , UNIT_MODEL , VOLUME_MONTH ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

CREATE INDEX IX_R_WS_PACKING_MOVEMENT1 on TB_R_WS_PACKING_MOVEMENT (VERSION, GETSUDO_MONTH, TIMING, VEHICLE_PLANT, VEHICLE_MODEL, UNIT_PLANT, UNIT_TYPE, UNIT_MODEL, VOLUME_MONTH)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
--
-- Creating table TB_R_RUNDOWN_KOMPO_STS
-- ===============================
--

CREATE TABLE "TB_R_RUNDOWN_KOMPO_STS" (
"VERSION" VARCHAR2 (10) NOT NULL,
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"VEHICLE_PLANT" VARCHAR2 (20) NOT NULL,
"VEHICLE_MODEL" VARCHAR2 (30) NOT NULL,
"UNIT_PLANT" VARCHAR2 (20) NOT NULL,
"UNIT_TYPE" VARCHAR2 (20) NOT NULL,
"UNIT_MODEL" VARCHAR2 (30) NOT NULL,
"UPLOAD_TYPE" VARCHAR2 (1) NOT NULL,
"UPLOAD_STS" VARCHAR2 (2),
"ROUND_FLAG" VARCHAR2 (1),
"UPLOAD_FILE_NAME" VARCHAR2 (270),
"APL_ID" VARCHAR2 (10),
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_R_RUNDOWN_KOMPO_STS ADD CONSTRAINT PK_R_RUNDOWN_KOMPO_STS PRIMARY KEY (VERSION , GETSUDO_MONTH , TIMING , VEHICLE_PLANT , VEHICLE_MODEL , UNIT_PLANT , UNIT_MODEL ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

CREATE INDEX IX_R_RUNDOWN_KOMPO_STS1 on TB_R_RUNDOWN_KOMPO_STS (VERSION, GETSUDO_MONTH, TIMING, VEHICLE_PLANT, VEHICLE_MODEL, UNIT_PLANT, UNIT_TYPE, UNIT_MODEL)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
--
-- Creating table TB_R_PAMS_RUNDOWN
-- ===============================
--

CREATE TABLE "TB_R_PAMS_RUNDOWN" (
"VERSION" VARCHAR2 (10) NOT NULL,
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"VEHICLE_PLANT" VARCHAR2 (20) NOT NULL,
"VEHICLE_MODEL" VARCHAR2 (30) NOT NULL,
"UNIT_PLANT" VARCHAR2 (20) NOT NULL,
"UNIT_MODEL" VARCHAR2 (30) NOT NULL,
"FILE_ID" VARCHAR2 (50) NOT NULL,
"FILE_NAME" VARCHAR2 (50) NOT NULL,
"IMPORTER" VARCHAR2 (5) NOT NULL,
"RUNDOWN_KEY" VARCHAR2 (70) NOT NULL,
"VARIATION" VARCHAR2 (10),
"SS_NO" VARCHAR2 (2),
"ID_LINE" VARCHAR2 (2),
"EXPORTER" VARCHAR2 (5) NOT NULL,
"ORDER_DT" DATE  NOT NULL,
"PROD_DT" DATE  NOT NULL,
"PROD_VOLUME" NUMBER (5) NOT NULL,
"LOCAL_STOCK" NUMBER (5) NOT NULL,
"STOCK_DAYS" NUMBER (4,2) NOT NULL,
"UNLOAD" NUMBER (5),
"TRANSIT" NUMBER (5),
"LOADING" NUMBER (5),
"PORT_STOCK" NUMBER (5),
"PACK_VOLUME" NUMBER (5) NOT NULL,
"LOT_SIZE" NUMBER (5),
"NO_OF_LOT" NUMBER (5),
"TOTAL_STOCK" NUMBER (5) NOT NULL,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_R_PAMS_RUNDOWN ADD CONSTRAINT PK_R_PAMS_RUNDOWN PRIMARY KEY (VERSION , GETSUDO_MONTH , TIMING , VEHICLE_PLANT , VEHICLE_MODEL , UNIT_PLANT , UNIT_MODEL , PROD_DT ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_R_KOMPO
-- ===============================
--

CREATE TABLE "TB_R_KOMPO" (
"VERSION" VARCHAR2 (10) NOT NULL,
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"VEHICLE_PLANT" VARCHAR2 (20) NOT NULL,
"VEHICLE_MODEL" VARCHAR2 (30) NOT NULL,
"UNIT_PLANT" VARCHAR2 (20) NOT NULL,
"UNIT_MODEL" VARCHAR2 (30) NOT NULL,
"FILE_ID" VARCHAR2 (50) NOT NULL,
"FILE_NAME" VARCHAR2 (50) NOT NULL,
"IMPORTER" VARCHAR2 (5),
"RUNDOWN_KEY" VARCHAR2 (70),
"EXPORTER" VARCHAR2 (5) NOT NULL,
"ORDER_DT" DATE  NOT NULL,
"VANNING_VOLUME" NUMBER (5) NOT NULL,
"VANNING_DT" DATE  NOT NULL,
"LOADING_DT" DATE  NOT NULL,
"UNLOADING_DT" DATE  NOT NULL,
"PROD_DT" DATE  NOT NULL,
"PROD_VOLUME" NUMBER (5) NOT NULL,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_R_KOMPO ADD CONSTRAINT PK_R_KOMPO PRIMARY KEY (VERSION , GETSUDO_MONTH , TIMING , VEHICLE_PLANT , VEHICLE_MODEL , UNIT_PLANT , UNIT_MODEL , VANNING_DT , PROD_DT ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_R_KOMPO_VAN_RESULT
-- ===============================
--

CREATE TABLE "TB_R_KOMPO_VAN_RESULT" (
"VERSION" VARCHAR2 (10) NOT NULL,
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"VEHICLE_PLANT" VARCHAR2 (20) NOT NULL,
"VEHICLE_MODEL" VARCHAR2 (30) NOT NULL,
"UNIT_PLANT" VARCHAR2 (20) NOT NULL,
"UNIT_MODEL" VARCHAR2 (30) NOT NULL,
"LOT_SIZE" NUMBER (3),
"VANNING_MONTH" VARCHAR2 (6) NOT NULL,
"VANNING_VOLUME" NUMBER (5) NOT NULL,
"ROUNDING_VOLUME" NUMBER (5),
"ADJUST_VOLUME" NUMBER (5),
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_R_KOMPO_VAN_RESULT ADD CONSTRAINT PK_R_KOMPO_VAN_RESULT PRIMARY KEY (VERSION , GETSUDO_MONTH , TIMING , VEHICLE_PLANT , VEHICLE_MODEL , UNIT_PLANT , UNIT_MODEL , VANNING_MONTH ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_R_CAPA_RESULT
-- ===============================
--

CREATE TABLE "TB_R_CAPA_RESULT" (
"VERSION" VARCHAR2 (10) NOT NULL,
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"VEHICLE_PLANT" VARCHAR2 (20) NOT NULL,
"VEHICLE_MODEL" VARCHAR2 (30) NOT NULL,
"UNIT_PLANT" VARCHAR2 (20) NOT NULL,
"UNIT_MODEL" VARCHAR2 (30) NOT NULL,
"UNIT_PARENT_LINE" VARCHAR2 (5) NOT NULL,
"INCOMING_VOL_STS" VARCHAR2 (2) NOT NULL,
"REMARK" VARCHAR2 (2),
"CONFIRMED_FLAG" VARCHAR2 (1) NOT NULL,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_R_CAPA_RESULT ADD CONSTRAINT PK_R_CAPA_RESULT PRIMARY KEY (VERSION , GETSUDO_MONTH , TIMING , VEHICLE_PLANT , VEHICLE_MODEL , UNIT_PLANT , UNIT_MODEL , UNIT_PARENT_LINE ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

CREATE INDEX IX_R_CAPA_RESULT1 on TB_R_CAPA_RESULT (VERSION, GETSUDO_MONTH, TIMING, VEHICLE_PLANT, VEHICLE_MODEL)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
CREATE INDEX IX_R_CAPA_RESULT2 on TB_R_CAPA_RESULT (VERSION, GETSUDO_MONTH, TIMING, UNIT_PLANT, UNIT_PARENT_LINE)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
--
-- Creating table TB_R_MULTI_LINE_SPLITING
-- ===============================
--

CREATE TABLE "TB_R_MULTI_LINE_SPLITING" (
"VERSION" VARCHAR2 (10) NOT NULL,
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"UNIT_PLANT" VARCHAR2 (20) NOT NULL,
"UNIT_PARENT_LINE" VARCHAR2 (5) NOT NULL,
"UNIT_SUB_LINE" VARCHAR2 (5) NOT NULL,
"UNIT_MODEL" VARCHAR2 (30) NOT NULL,
"VOLUME_MONTH" VARCHAR2 (6) NOT NULL,
"SPLITING_VOLUME" NUMBER (5),
"SUB_LINE_CAPA_RESULT" VARCHAR2 (2),
"UPLOAD_FILE_NAME" VARCHAR2 (270),
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_R_MULTI_LINE_SPLITING ADD CONSTRAINT PK_R_MULTI_LINE_SPLITING PRIMARY KEY (VERSION , GETSUDO_MONTH , TIMING , UNIT_PLANT , UNIT_PARENT_LINE , UNIT_SUB_LINE , UNIT_MODEL , VOLUME_MONTH ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

CREATE INDEX IX_R_MULTI_LINE_SPLITING1 on TB_R_MULTI_LINE_SPLITING (VERSION, GETSUDO_MONTH, TIMING, UNIT_PLANT, UNIT_PARENT_LINE)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
--
-- Creating table TB_S_CALENDAR
-- ===============================
--

CREATE TABLE "TB_S_CALENDAR" (
"GETSUDO_MONTH" VARCHAR2 (6),
"TIMING" VARCHAR2 (4),
"PLANT" VARCHAR2 (20),
"CALENDAR_DT" DATE ,
"CALENDAR_FLAG" VARCHAR2 (1),
"APL_ID" VARCHAR2 (10),
"RUNNING_NO" NUMBER (5),
"CREATE_BY" VARCHAR2 (20))
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);


--
-- Creating table TB_S_UNIT_PLANT_CAPA
-- ===============================
--

CREATE TABLE "TB_S_UNIT_PLANT_CAPA" (
"GETSUDO_MONTH" VARCHAR2 (6),
"TIMING" VARCHAR2 (4),
"UNIT_PLANT" VARCHAR2 (20),
"UNIT_PARENT_LINE" VARCHAR2 (5),
"UNIT_SUB_LINE" VARCHAR2 (5),
"UNIT_CAPA_MONTH" VARCHAR2 (6),
"MONTHLY_CAPA" NUMBER (5),
"DAILY_CAPA" NUMBER (5),
"WORKING_DAY" NUMBER (2),
"WORKING_TIME" NUMBER (3),
"WORKING_SHIFT" NUMBER (1),
"TAKT_TIME" NUMBER (4,2),
"EFFICIENCY" NUMBER (5,2),
"DAILY_OT" NUMBER (4,2),
"HOLIDAY_OT" NUMBER (2),
"SPECIAL_EFFORT" NUMBER (4),
"APL_ID" VARCHAR2 (10),
"RUNNING_NO" NUMBER (5),
"CREATE_BY" VARCHAR2 (20))
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);


--
-- Creating table TB_S_KAIKIENG
-- ===============================
--

CREATE TABLE "TB_S_KAIKIENG" (
"VERSION" VARCHAR2 (10),
"GETSUDO_MONTH" VARCHAR2 (6),
"TIMING" VARCHAR2 (4),
"VEHICLE_PLANT" VARCHAR2 (20),
"VEHICLE_MODEL" VARCHAR2 (30),
"VOLUME_MONTH" VARCHAR2 (6),
"VEHICLE_VOLUME" NUMBER (5),
"UNIT_TYPE" VARCHAR2 (20),
"UNIT_MODEL" VARCHAR2 (30),
"UNIT_VOLUME" NUMBER (5),
"UPLOAD_FILE_NAME" VARCHAR2 (270),
"APL_ID" VARCHAR2 (10),
"RUNNING_NO" NUMBER (5),
"CREATE_BY" VARCHAR2 (20))
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);


--
-- Creating table TB_S_WS_MULTI_SOURCE_UNITS
-- ===============================
--

CREATE TABLE "TB_S_WS_MULTI_SOURCE_UNITS" (
"GETSUDO_MONTH" VARCHAR2 (6),
"TIMING" VARCHAR2 (4),
"VEHICLE_PLANT" VARCHAR2 (20),
"VEHICLE_MODEL" VARCHAR2 (30),
"UNIT_PLANT" VARCHAR2 (20),
"UNIT_MODEL" VARCHAR2 (30),
"VOLUME_MONTH" VARCHAR2 (6),
"UNIT_VOLUME" NUMBER (5),
"UPLOAD_FILE_NAME" VARCHAR2 (270),
"APL_ID" VARCHAR2 (10),
"RUNNING_NO" NUMBER (5),
"CREATE_BY" VARCHAR2 (20))
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);


--
-- Creating table TB_S_WS_PACKING_MOVEMENT
-- ===============================
--

CREATE TABLE "TB_S_WS_PACKING_MOVEMENT" (
"GETSUDO_MONTH" VARCHAR2 (6),
"TIMING" VARCHAR2 (4),
"VEHICLE_PLANT" VARCHAR2 (20),
"VEHICLE_MODEL" VARCHAR2 (30),
"UNIT_PLANT" VARCHAR2 (20),
"UNIT_TYPE" VARCHAR2 (20),
"UNIT_MODEL" VARCHAR2 (30),
"VOLUME_MONTH" VARCHAR2 (6),
"PACKING_VOLUME" NUMBER (5),
"UPLOAD_FILE_NAME" VARCHAR2 (270),
"APL_ID" VARCHAR2 (10),
"RUNNING_NO" NUMBER (5),
"CREATE_BY" VARCHAR2 (20))
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);


--
-- Creating table TB_S_PAMS_RUNDOWN
-- ===============================
--

CREATE TABLE "TB_S_PAMS_RUNDOWN" (
"GETSUDO_MONTH" VARCHAR2 (6),
"TIMING" VARCHAR2 (4),
"VEHICLE_PLANT" VARCHAR2 (20),
"VEHICLE_MODEL" VARCHAR2 (30),
"UNIT_PLANT" VARCHAR2 (20),
"UNIT_MODEL" VARCHAR2 (30),
"FILE_ID" VARCHAR2 (50),
"FILE_NAME" VARCHAR2 (50),
"IMPORTER" VARCHAR2 (5),
"RUNDOWN_KEY" VARCHAR2 (70),
"VARIATION" VARCHAR2 (10),
"SS_NO" VARCHAR2 (2),
"ID_LINE" VARCHAR2 (2),
"EXPORTER" VARCHAR2 (5),
"ORDER_DT" DATE ,
"PROD_DT" DATE ,
"PROD_VOLUME" NUMBER (5),
"LOCAL_STOCK" NUMBER (5),
"STOCK_DAYS" NUMBER (4,2),
"UNLOAD" NUMBER (5),
"TRANSIT" NUMBER (5),
"LOADING" NUMBER (5),
"PORT_STOCK" NUMBER (5),
"PACK_VOLUME" NUMBER (5),
"LOT_SIZE" NUMBER (5),
"NO_OF_LOT" NUMBER (5),
"TOTAL_STOCK" NUMBER (5),
"UPLOAD_FILE_NAME" VARCHAR2 (270),
"APL_ID" VARCHAR2 (10),
"RUNNING_NO" NUMBER (5),
"CREATE_BY" VARCHAR2 (20))
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);


--
-- Creating table TB_S_KOMPO
-- ===============================
--

CREATE TABLE "TB_S_KOMPO" (
"GETSUDO_MONTH" VARCHAR2 (6),
"TIMING" VARCHAR2 (4),
"VEHICLE_PLANT" VARCHAR2 (20),
"VEHICLE_MODEL" VARCHAR2 (30),
"UNIT_PLANT" VARCHAR2 (20),
"UNIT_MODEL" VARCHAR2 (30),
"FILE_ID" VARCHAR2 (50),
"FILE_NAME" VARCHAR2 (50),
"IMPORTER" VARCHAR2 (5),
"RUNDOWN_KEY" VARCHAR2 (70),
"EXPORTER" VARCHAR2 (5),
"ORDER_DT" DATE ,
"VANNING_VOLUME" NUMBER (5),
"VANNING_DT" DATE ,
"LOADING_DT" DATE ,
"UNLOADING_DT" DATE ,
"PROD_DT" DATE ,
"PROD_VOLUME" NUMBER (5),
"UPLOAD_FILE_NAME" VARCHAR2 (270),
"APL_ID" VARCHAR2 (10),
"RUNNING_NO" NUMBER (5),
"CREATE_BY" VARCHAR2 (20))
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);


--
-- Creating table TB_S_MULTI_LINE_SPLITING
-- ===============================
--

CREATE TABLE "TB_S_MULTI_LINE_SPLITING" (
"GETSUDO_MONTH" VARCHAR2 (6),
"TIMING" VARCHAR2 (4),
"UNIT_PLANT" VARCHAR2 (20),
"UNIT_PARENT_LINE" VARCHAR2 (5),
"UNIT_SUB_LINE" VARCHAR2 (5),
"UNIT_MODEL" VARCHAR2 (30),
"VOLUME_MONTH" VARCHAR2 (6),
"SPLITING_VOLUME" NUMBER (5),
"UPLOAD_FILE_NAME" VARCHAR2 (270),
"APL_ID" VARCHAR2 (10),
"RUNNING_NO" NUMBER (5),
"CREATE_BY" VARCHAR2 (20))
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);


--
-- Creating table TB_P_KAIKIENG_H
-- ===============================
--

CREATE TABLE "TB_P_KAIKIENG_H" (
"VERSION" VARCHAR2 (10) NOT NULL,
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"VEHICLE_PLANT" VARCHAR2 (20) NOT NULL,
"VEHICLE_MODEL" VARCHAR2 (30) NOT NULL,
"VOLUME_MONTH" VARCHAR2 (6) NOT NULL,
"VEHICLE_VOLUME" NUMBER (5),
"KAIKIENG_FILE_NAME" VARCHAR2 (270),
"WORKSHEET_FILE_NAME" VARCHAR2 (270),
"SUBMIT_DT" DATE ,
"REJECT_DT" DATE ,
"KAIKIENG_STATUS" VARCHAR2 (2) NOT NULL,
"WORKSHEET_STATUS" VARCHAR2 (2),
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_P_KAIKIENG_H ADD CONSTRAINT PK_P_KAIKIENG_H PRIMARY KEY (VERSION , GETSUDO_MONTH , TIMING , VEHICLE_PLANT , VEHICLE_MODEL , VOLUME_MONTH , CREATE_BY ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_P_KAIKIENG_D
-- ===============================
--

CREATE TABLE "TB_P_KAIKIENG_D" (
"VERSION" VARCHAR2 (10) NOT NULL,
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"VEHICLE_PLANT" VARCHAR2 (20) NOT NULL,
"VEHICLE_MODEL" VARCHAR2 (30) NOT NULL,
"UNIT_TYPE" VARCHAR2 (20) NOT NULL,
"UNIT_MODEL" VARCHAR2 (30) NOT NULL,
"VOLUME_MONTH" VARCHAR2 (6) NOT NULL,
"UNIT_VOLUME" NUMBER (5),
"MULTI_SOURCE_FLAG" VARCHAR2 (1) NOT NULL,
"MULTI_SUB_LINE_FLAG" VARCHAR2 (1) NOT NULL,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_P_KAIKIENG_D ADD CONSTRAINT PK_P_KAIKIENG_D PRIMARY KEY (VERSION , GETSUDO_MONTH , TIMING , VEHICLE_PLANT , VEHICLE_MODEL , UNIT_MODEL , VOLUME_MONTH , CREATE_BY ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

CREATE INDEX IX_P_KAIKIENG_D1 on TB_P_KAIKIENG_D (VERSION, GETSUDO_MONTH, TIMING, VEHICLE_PLANT, VEHICLE_MODEL, UNIT_TYPE, UNIT_MODEL, VOLUME_MONTH)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
--
-- Creating table TB_L_UPLOAD_STS
-- ===============================
--

CREATE TABLE "TB_L_UPLOAD_STS" (
"UPLOAD_TYPE" VARCHAR2 (20) NOT NULL,
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"VEHICLE_PLANT" VARCHAR2 (20),
"UNIT_PLANT" VARCHAR2 (20),
"VEHICLE_MODEL" VARCHAR2 (30),
"UNIT_MODEL" VARCHAR2 (30),
"UNIT_PARENT_LINE" VARCHAR2 (10),
"UNIT_SUB_LINE" VARCHAR2 (10),
"FILE_NAME" VARCHAR2 (270),
"MODULE_ID" VARCHAR2 (10),
"FUNCTION_ID" VARCHAR2 (10),
"APL_ID" VARCHAR2 (10),
"STATUS" VARCHAR2 (1) NOT NULL,
"MESSAGE" VARCHAR2 (100) NOT NULL,
"TRANS_UPDATE_DT" TIMESTAMP ,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_L_UPLOAD_STS ADD CONSTRAINT PK_L_UPLOAD_STS PRIMARY KEY (APL_ID ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_L_UPLOAD_DETAIL
-- ===============================
--

CREATE TABLE "TB_L_UPLOAD_DETAIL" (
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"VEHICLE_PLANT" VARCHAR2 (20) NOT NULL,
"VEHICLE_MODEL" VARCHAR2 (30) NOT NULL,
"UNIT_PLANT" VARCHAR2 (20) NOT NULL,
"UNIT_MODEL" VARCHAR2 (30) NOT NULL,
"ERROR_SHEET" VARCHAR2 (1) NOT NULL,
"RUNNING_NO" NUMBER (5) NOT NULL,
"ERROR_DATE" VARCHAR2 (10),
"ERROR_MONTH" VARCHAR2 (6),
"ERROR_RUNDOWN" VARCHAR2 (20),
"ERROR_CALENDAR" VARCHAR2 (20),
"ERROR_WORKSHEET" NUMBER (5),
"ERROR_STOCK_MIN" NUMBER (4,2),
"ERROR_STOCK_MAX" NUMBER (4,2),
"APL_ID" VARCHAR2 (10) NOT NULL,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_L_UPLOAD_DETAIL ADD CONSTRAINT PK_L_UPLOAD_DETAIL PRIMARY KEY (GETSUDO_MONTH , TIMING , VEHICLE_PLANT , VEHICLE_MODEL , UNIT_PLANT , UNIT_MODEL , ERROR_SHEET , RUNNING_NO ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

CREATE INDEX IX_L_UPLOAD_DETAIL1 on TB_L_UPLOAD_DETAIL (APL_ID)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
--
-- Creating table TB_L_LOGGER
-- ===============================
--

CREATE TABLE "TB_L_LOGGER" (
"D_HODTCRE" DATE  NOT NULL,
"N_SEQ_NO" NUMBER (9) NOT NULL,
"V_APL_ID" VARCHAR2 (10),
"V_MODULE_ID" VARCHAR2 (10) NOT NULL,
"V_FUNCTION_ID" VARCHAR2 (10) NOT NULL,
"V_USERCRE" VARCHAR2 (20) NOT NULL,
"V_MESSAGE_TYPE" VARCHAR2 (1) NOT NULL,
"V_MESSAGE_CODE" VARCHAR2 (12),
"V_MESSAGE" VARCHAR2 (2000) NOT NULL,
"V_STATUS" VARCHAR2 (1))
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_L_LOGGER ADD CONSTRAINT PK_L_LOGGER PRIMARY KEY (N_SEQ_NO ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_M_MODULE_H
-- ===============================
--

CREATE TABLE "TB_M_MODULE_H" (
"V_MODULE_ID" VARCHAR2 (10) NOT NULL,
"V_MODULE_NAME" VARCHAR2 (100),
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_M_MODULE_H ADD CONSTRAINT PK_M_MODULE_H PRIMARY KEY (V_MODULE_ID ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_M_MODULE_D
-- ===============================
--

CREATE TABLE "TB_M_MODULE_D" (
"V_MODULE_ID" VARCHAR2 (10) NOT NULL,
"V_FUNCTION_ID" VARCHAR2 (10) NOT NULL,
"V_FUNCTION_NAME" VARCHAR2 (100),
"V_ERROR_FLAG" CHAR (1),
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_M_MODULE_D ADD CONSTRAINT PK_M_MODULE_D PRIMARY KEY (V_MODULE_ID , V_FUNCTION_ID ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_M_SYSTEM
-- ===============================
--

CREATE TABLE "TB_M_SYSTEM" (
"CATEGORY" VARCHAR2 (40) NOT NULL,
"SUB_CATEGORY" VARCHAR2 (40) NOT NULL,
"CD" VARCHAR2 (40) NOT NULL,
"VALUE" VARCHAR2 (200) NOT NULL,
"REMARK" VARCHAR2 (200),
"STATUS" VARCHAR2 (1) NOT NULL,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_M_SYSTEM ADD CONSTRAINT PK_M_SYSTEM PRIMARY KEY (CATEGORY , SUB_CATEGORY , CD ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

CREATE INDEX IX_M_SYSTEM1 on TB_M_SYSTEM (CATEGORY, SUB_CATEGORY, CD, VALUE, STATUS)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
CREATE INDEX IX_M_SYSTEM2 on TB_M_SYSTEM (CATEGORY, SUB_CATEGORY, STATUS)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
--
-- Creating table TB_R_BATCH_PARAMETER
-- ===============================
--

CREATE TABLE "TB_R_BATCH_PARAMETER" (
"PARAM_ID" VARCHAR2 (6),
"REQUEST_ID" VARCHAR2 (8),
"BATCH_ID" VARCHAR2 (10),
"PARAMETERS" VARCHAR2 (200),
"PROJECT_CODE" CHAR (3),
"SUPPORT_ID" VARCHAR2 (10),
"REQUEST_BY" VARCHAR2 (20),
"REQUEST_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);


--
-- Creating table TB_R_BATCH_QUEUE
-- ===============================
--

CREATE TABLE "TB_R_BATCH_QUEUE" (
"QUEUE_NO" NUMBER (22,0),
"REQUEST_ID" VARCHAR2 (8),
"BATCH_ID" VARCHAR2 (10),
"REQUEST_DATE" DATE ,
"REQUEST_BY" VARCHAR2 (10),
"PARAMETERS" VARCHAR2 (200),
"SUPPORT_ID" VARCHAR2 (10),
"PROJECT_CODE" CHAR (3),
"DESCRIPTION" VARCHAR2 (200),
"APP_ID" VARCHAR2 (10))
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);


--
-- Creating table TB_M_SEQ
-- ===============================
--

CREATE TABLE "TB_M_SEQ" (
"SEQ_CODE" VARCHAR2 (20) NOT NULL,
"SEQ_KEY" VARCHAR2 (10) NOT NULL,
"CURRENT_VALUE" NUMBER (10,0) NOT NULL,
"START_VALUE" NUMBER (10,0) NOT NULL,
"DOC_NO_FORMAT" VARCHAR2 (50) NOT NULL,
"START_MONTH" NUMBER (2,0) NOT NULL,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL,
"VERSION" NUMBER (10,0))
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_M_SEQ ADD CONSTRAINT PK_M_SEQ PRIMARY KEY (SEQ_CODE ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_M_HIST_SEQ
-- ===============================
--

CREATE TABLE "TB_M_HIST_SEQ" (
"SEQ_CODE" VARCHAR2 (20) NOT NULL,
"SEQ_KEY" VARCHAR2 (10) NOT NULL,
"CURRENT_VALUE" NUMBER (10,0) NOT NULL,
"START_VALUE" NUMBER (10,0) NOT NULL,
"DOC_NO_FORMAT" VARCHAR2 (50) NOT NULL,
"START_MONTH" NUMBER (2,0) NOT NULL,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL,
"HISTORY_KEY" VARCHAR2 (10) NOT NULL,
"VERSION" NUMBER (10,0))
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_M_HIST_SEQ ADD CONSTRAINT PK_M_HIST_SEQ PRIMARY KEY (SEQ_CODE , HISTORY_KEY ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

