prompt Disabling triggers for TB_L_EXCEL_DOWNLOAD_FILE...
alter table TB_L_EXCEL_DOWNLOAD_FILE disable all triggers;
prompt Loading TB_L_EXCEL_DOWNLOAD_FILE...
prompt Table is empty
prompt Enabling triggers for TB_L_EXCEL_DOWNLOAD_FILE...
alter table TB_L_EXCEL_DOWNLOAD_FILE enable all triggers;
